name: deploy cyberpaper

on:
  push:
    branches: [ 'master' ]

  pull_request:
    branches: [ 'master' ]

jobs:
  build-image:
    runs-on: self-hosted
    steps:
      - name: Prepare
        shell: sh
        run: |
          apk update
          apk add nodejs docker-cli docker-cli-buildx
          apk add kubectl

      - name: Checkout repository
        uses: https://github.com/actions/checkout@master
        with:
          submodules: 'recursive'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: kubernetes

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ gitea.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-  

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@master
        with:
          file: Dockerfile
          push: true
          tags: vistee/pprfnk:cyberpaperbot

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Kubernetes context
        uses: Azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}
          context: kubernetes-admin@kubernetes
          namespace: nastya

      - name: Rollout pod in k8s
        run: kubectl rollout restart -n cyberpaper deployment cyberpaper-bot
