name: Deploy

on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ 'master' ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Stop Cyber Paper
        run: systemctl stop cyberpaper && kill -s 9 $(pidof /home/cyberpaper/bin/python)
      - name: Start cyberpaper
        run: systemctl start cyberpaper