name: Deploy

on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ 'master' ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Stop Cyber Paper bot
        run: systemctl stop cyberpaper && kill -s 9 $(pidof /home/cyberpaper/bin/python)

      - name: Pull Cyber Paper source
        run: cd /opt/cyberpaper && git pull

      - name: Start Cyber Paper bot
        run: systemctl start cyberpaper