name: Deploy

on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ 'master' ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Setup SSH passphrase
        env:
          SSH_PASSPHRASE: ${{secrets.SSH_PASSPHRASE}}
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
        run: |
          echo '#!/bin/sh' > ~/.ssh_askpass echo 'echo $SSH_PASSPHRASE' >> ~/.ssh_askpass && chmod +x ~/.ssh_askpass echo "$SSH_PRIVATE_KEY" | tr -d '\r' | DISPLAY=None SSH_ASKPASS=~/.ssh_askpass ssh-add - >/dev/null

      - name: Print ssh-add identities
        run: ssh-add -l

      - name: Stop Cyber Paper bot
        run: systemctl stop cyberpaper

      - name: Pull Cyber Paper source
        run: whoami && cd /opt/cyberpaper && git pull

      - name: Start Cyber Paper bot
        run: systemctl start cyberpaper
